# configs/otel-collector.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  prometheus/dcgm:
    config:
      scrape_configs:
        - job_name: dcgm-exporter
          scrape_interval: 5s
          static_configs:
            - targets: ["dcgm-exporter:9400"]

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: {}
      memory: {}

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [10, 50, 100, 500, 1000, 2000, 5000, 10000]
    metrics_flush_interval: 5s

processors:
  batch:
    send_batch_size: 1024
    timeout: 5s

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: ""

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus/dcgm, hostmetrics, spanmetrics]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, spanmetrics]
