apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- route.yaml
- otel-configmap.yaml
- otel-collector.yaml
- servicemonitor.yaml
- monitoringstack.yaml
- grafana.yaml

commonLabels:
  app.kubernetes.io/part-of: vjepa2
