apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: vjepa2
  labels:
    app: otel-collector
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: vjepa2
spec:
  selector:
    matchLabels:
      app: otel-collector
  endpoints:
  - port: metrics
    interval: 15s
